### ISSUE TITLE
Allow user to upload a file containing a list of genes to interrogate

### ISSUE THREAD

**Issue by bhavyaac** [fungenomics/braindex#17]
If this is implemented, the app will need to provide informative error messages on whether uploaded genes exist or not in the database - see issue #1

**Comment by bhavyaac** [comment]
Just managed to set this up! Some notes on my implementation for future me are below - I hope to include the relevant parts for the user in a future landing page!
- The upload button is right below the original text box to enter gene names
- The button will only accept csv & tsv files - the file browser that opens will default to only displaying those file types. If any other file type is uploaded, an error message will state "Invalid file; Please upload a .csv or .tsv file"
- The format of the csv file doesn't matter - I have tested the function with genes placed vertically in an excel column as well as genes placed horizontally in the same row, and both will work. I have not tested this with tsv files yet
- The gene names in the file (if provided) are appended (i.e. placed after) the genes in the text box (if any), and any duplicates are removed (i.e. only the first instance of the gene will be preserved). The previous limit of 20 genes holds for the combined list of genes from both inputs.
-  A warning message to the user "Please enter a gene" will be displayed if the text box is empty AND no file has been uploaded

I still need to work on creating an error message for genes that do not exist in the database.

**Comment by sjessa** [comment]
@bhavyaac Nice, thanks for the notes & details! This sounds great ☺️ Here are a couple comments:

- The main suggestion I would make is to use as input either the text box OR the file, if that's doable on the back-end! To me, it seems a bit unintuitive to append them, and to not have to clear any genes in the input box if a user decides to use a gene file (so the file would take precedence over text box input)
- That's cool that the formatting of the input file works either way! I think even if this is the case, I'd still specify a preferred formatting in the docs, that way we give people just one option and don't invite any confusion 🙂

**Comment by bhavyaac** [comment]
>     The main suggestion I would make is to use as input either the text box OR the file, if that's doable on the back-end! To me, it seems a bit unintuitive to append them, and to not have to clear any genes in the input box if a user decides to use a gene file (so the file would take precedence over text box input)

This makes a lot of sense. I'll work on creating a toggle for the user to choose between textbox input and gene list upload. I can condition which data is used in the app based on the state of the toggle, so only one would ever be used at a time. Let me know if that fits what you had in mind.

>     That's cool that the formatting of the input file works either way! I think even if this is the case, I'd still specify a preferred formatting in the docs, that way we give people just one option and don't invite any confusion 🙂

This makes sense for sure! One other thing I would add to the docs is that I used certain encodings (UTF-8 for reading, UTF-8 BOM to remove extra lines associated with the file type when passing as input to the code). This works with the test files I used, which were csv files that I saved through Excel. If the file that the user provides is created with a different encoding, the file input won't work, and I'm not sure if there's a way to detect the encoding and respond with an error message, so it would be great if we could inform the user about this in the docs.

**Comment by bhavyaac** [comment]
Here is a gif preview of the toggle function! 
![toggle_file_upload](https://user-images.githubusercontent.com/26724860/124627561-a8286600-de4d-11eb-80d6-94da0896a2c2.gif)

**Comment by bhavyaac** [comment]
Something else to add to file upload documentation:
The URL bookmarking system doesn't save the gene input(s) from the file, only the current state of the textbox inputs. On the other hand, the server-side bookmarking system _seems_ to store the gene inputs from the file within the bookmarked page. (I tested this locally, but it might also be related to Shiny's tendency to cache input files instead of the bookmark storage...)

**Comment by bhavyaac** [comment]
I've just implemented a basic error message for genes that are not in the database. It works by comparing all of the gene names (i.e. strings) in the file with the list of genes that are provided as choices in the textbox. The next step would be to check against the annotation as well, as mentioned in issue #1. Some details:
- Since the timecourse tab only plots the first gene, the error message for this tab only checks the first gene in the file
- The (new) ranked clusters tab will check the first gene only, unless the mean expression toggle is on, in which case it will check all of the genes provided

This is what it looks like. I'm still trying to find a way to hide download button(s) if the error message was triggered, any ideas would be great!
![image](https://user-images.githubusercontent.com/26724860/124680773-1a706900-de95-11eb-86bd-cfca7f2f2fcf.png)

**Comment by bhavyaac** [comment]
Another note for documentation: the gene input is **case sensitive**, so genes that are capitalized differently will also produce `validate()` errors! 
See issue #1 for more discussion on making the validation more user-friendly by providing more detailed error messages.

**Comment by sjessa** [comment]
@bhavyaac 

> This is what it looks like. I'm still trying to find a way to hide download button(s) if the error message was triggered, any ideas would be great!

Maybe we can discuss this one when we meet -- if I understand correctly, we need to find a way for the download handlers to listen for the `validate()` output- we can do some brainstorming!
