### ISSUE TITLE
Add visualization(s) of clusters ranked by mean expression of input gene

### ISSUE THREAD

**Issue by sjessa** [fungenomics/braindex#20]
Two possibilities that could be useful:

Option 1 - bar plot with GSEA-style ticks
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12974417/122500306-8cedd780-cfc0-11eb-846a-b8741e5dfa9a.png">

Option 2 - ranked dot plot
<img width="412" alt="image" src="https://user-images.githubusercontent.com/12974417/122500392-b870c200-cfc0-11eb-87f5-346f7de55495.png">

**Comment by bhavyaac** [comment]
I will try the bar plot (first suggestion) with ticks & place it in a separate tab. Not sure about tab title, maybe "Ranked expression by cluster"..?

**Comment by sjessa** [comment]
@bhavyaac I like your edit version!!

**Comment by bhavyaac** [comment]
Here's a screenshot of the current "look" of this tab. @sjessa do you think it would help to add a toggle to plot the mean expression of all of the genes entered (instead of the first gene only)? Also, let me know if you have any suggestions for the plot formatting / any other functionalities!

![image](https://user-images.githubusercontent.com/26724860/124629085-16b9f380-de4f-11eb-9a09-f1d6d523e41b.png)

**Comment by sjessa** [comment]
@bhavyaac Nice, this looks great! If it's easy to add a toggle for mean expression, I don't think that would hurt at all, especially if we are already calculating it.

In terms of aesthetics, the only thing I can think of would be to potentially make the border color a light gray here in the top plot, perhaps with `theme_min(border_colour = "gray90")` or something like that, and then remove the border entirely around the ticks plot. And I'd reduce the x axis text a tiny bit in size so it's a little more readable! That's it :)

**Comment by bhavyaac** [comment]
Here is a still screenshot for the new formatting as well as a gif to show the mean expression toggle function. Let me know if this is better @sjessa!
![image](https://user-images.githubusercontent.com/26724860/124638626-2b02ee00-de59-11eb-8726-43e4901f4f25.png)
![toggle_ranked_meanexp](https://user-images.githubusercontent.com/26724860/124638566-1888b480-de59-11eb-8cdd-95d3d242500b.gif)

**Comment by sjessa** [comment]
@bhavyaac It's beautiful! I don't think I have anything more to add :)

**Comment by sjessa** [comment]
@bhavyaac Oh I spot one thing -- if we're plotting mean expression here, we should just change the y-axis label! (It's possible it was like this in my code, sorry!) I would just make it `glue("Mean {gene) expression")` or something like that

**Comment by bhavyaac** [comment]
In this case it's the mean over the proportion of cells, so should I write that ("Mean proportion of cells") instead? Or is mean expression OK?
