### ISSUE TITLE
Add ability to bookmark URL to capture current state of the app (using a button)

### ISSUE THREAD

**Issue by sjessa** [fungenomics/braindex#28]
See here for guide:
https://mastering-shiny.org/action-bookmark.html

**Comment by bhavyaac** [comment]
Should we implement this via url or server storage? And should we update the browser URL automatically as well?

**Comment by sjessa** [comment]
Good question! @CooberHoo has started looking into this and used a server-side, no-URL-update approach, which we think is the way to go since those URLs will get _very_ unwieldy. However, we've run into some issues with actually making this work on the server (i.e. the bookmarking occurs, but we can't use the URL to restore the state), so we have some debugging to do to make this functional!
